### PR TITLE
Firebase Snippets using GetX 

### PR DESCRIPTION
**Pull request by guled-flutter**
Can we kindly have some Firebase snippets for Auth,storage and analytics 

I bought you coffee 🤫

### CODE REVIEW

**Comment by kauemurakami** [comment]
hello my friend, very nice to find out that you are still here, I will work on it next week and send you a direct message in some way. thanks for contributing and for the coffee. I've already done some auths, and storage, but firebase changes a lot, I'll have to do some tests, and I'll add 😍

**Comment by guled-flutter** [comment]
Thanks bro
We will appreciate it
Especially for those who do not know Firebase with GetX

**Comment by kauemurakami** [comment]
I came to update you that I already got a solution, quick for that and I will be implementing this weekend. ☺️

**Comment by guled-flutter** [comment]
They updated Firebase already

**Comment by kauemurakami** [comment]
@guled-flutter 
I'm finishing this right now, tonight when updating the extension you will see several login-related snippets, next will be adding storage / cloud firestore

**Comment by kauemurakami** [comment]
is done !!

**Comment by kauemurakami** [comment]
Good morning my friend, I saw that you followed me on twitter, we can talk it via direct, or by telegram, send me your number via direct on twitter

**Pull request merged**
